### ISSUE TITLE
Created a repository

### ISSUE THREAD

**Issue by godbit** [Lapsang-boys/magic#1]
In mew playground me and Tank cant assign stuff or set lables etc. Hence i created this repo. It can also be used as a log of drafts, keep all issues in the same place. We would store old documents invitaions etc.

It can be used for:
- Issues for stuff that needs to be done before a draft
    - Assign the responsible person
    - Use labels
- Magic related code (if any)
    - Awsome example :heart_eyes: https://github.com/godbit/Magic
    - Code based formats etc

What do you think @karlek & @mewmew? Plz watch this repo so you get notifications :wink: Also, snacka svensk?

**Comment by karlek** [comment]
Sounds good, then we won't litter down mewmew/playground as well haha

**Comment by godbit** [comment]
Exactly my thoughts, that repo needs to maintain it pristine condition :zap:

**Comment by mewmew** [comment]
> In mew playground me and Tank cant assign stuff or set lables etc.

Haha, good point. In Lapsang-Boys, I don't think I can assign stuff or set labels though. Perhaps that's a feature and not a bug?

**Comment by karlek** [comment]
Def a bug, I'll fix!

**Comment by mewmew** [comment]
Yay, permissions for labels work now.
