### ISSUE TITLE
Guilds of Ravnica - Invitation

### ISSUE THREAD

**Issue by godbit** [Lapsang-boys/magic#2]
Make a pdf invitation to everyone with date etc. Also a nice picture is needed :rabbit: 

From mewmew playground:

Date - Lördag 13/10

Invite list:
- Micke
- Honke
- Danne
- Bob
- Bradley
- Johan (snubben från mitt jobb)

**Comment by godbit** [comment]
[guilds of ravnica inviation.pdf](https://github.com/Lapsang-boys/magic/files/2386117/guilds.of.ravnica.inviation.pdf)

Invitation sent

**Comment by mewmew** [comment]
> guilds of ravnica inviation.pdf

It's a great idea to add the invites as attachments, as we can then look back at previous drafts and reminisce. If we can find the old invites, it would be fun to retroactively add them to this repo. Perhaps even in the repo proper, by adding an invites folder or something.

**Comment by godbit** [comment]
Good idea :) ill see what i can find on my computer and in my mail box. Create a new issue and assign it to me. Ill set up a proper structure in the repo and push all files i can find

**Comment by mewmew** [comment]
Nu när det inte blir draft till helgen (13e/14e), ska vi köra ett **godbit coding camp montage**? Antingen lör eller sön? :)

**Comment by godbit** [comment]
Vi snackade lite med Bob om att köra brädspel, gameing, super smash osv (gött häng) istället för draft lördag 13/10 och sedan Avalon brunch 14/10 :D Vad tror du om det?

**Comment by mewmew** [comment]
> Vi snackade lite med Bob om att köra brädspel, gameing, super smash osv (gött häng) istället för draft lördag 13/10 och sedan Avalon brunch 14/10 :D Vad tror du om det?

Båda låter riktigt trevliga! Jag kommer gärna över någon av dagarna. Behöver säkert slakta lite plugg under helgen också. Hur går det med Go-spec'en btw? :)

**Comment by godbit** [comment]
Okej, vilken dag kommer du helst över? :) Haha det har inte hänt mycket på den fronten (och kommer nog inte göra på ett tag heller tyvärr :( )

**Comment by mewmew** [comment]
> Okej, vilken dag kommer du helst över? :) Haha det har inte hänt mycket på den fronten (och kommer nog inte göra på ett tag heller tyvärr :( )

Hehe, det är lugnt. Jag kikar gärna förbi på Lördag! Har en rad köttiga kurser nu, så hemtenta på sön o.O

**Comment by karlek** [comment]
Gött! Tekannan laddas och brädspelen dammas av inför att du kommer :dromedary_camel:
