### ISSUE TITLE
Invites from the past

### ISSUE THREAD

**Issue by mewmew** [Lapsang-boys/magic#3]
Lets preserve old invites, would be fun to look back at on a later date. And take ideas from when building new formats for drafts

**Comment by mewmew** [comment]
ping @godbit. Deadline set as part of the [Bergis Minidraft](https://github.com/Lapsang-boys/magic/milestone/1) milestone. Importance escalated to critical.

**Comment by godbit** [comment]
Issues with the Label critical will always be resolved within 6 h 🍦

**Comment by mewmew** [comment]
:icecream: :waffle:

**Comment by mewmew** [comment]
The response time of this crew is among the best in town.

**Comment by karlek** [comment]
```
Something strange,
In the latest commit
Who you gonna ping?
@godbit, @karlek
```
