### ISSUE TITLE
Tonight, dinner

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/magic#5]
Yo! 

Hur är planen med middag ikväll? Ska jag och Emil köpa något på vägen till hagis?

Kram

**Comment by mewmew** [comment]
Hej! Ehm, jag menar, var hälsad!

Morgonen i ära skickade jag försändelse per elektroniskt telegram till samtliga kumpaner i björnligan. Huruvida vi sammanstrålar eller ej är inom ramen för ett framtida beslut att avgöra. Ni är gladerligen välkomna och det finns i så fall getostlasagne till oss alla. Jag kommer nog inte kunna bidra till kvällens konversationer då rösten har beslutat att ta höstlov. Hur som, bastun är bokad och ni får själva avgöra kvällens öde :bear:

*björnkram*

**Comment by godbit** [comment]
Hola bröder!

Jag är tillgänglig för bastukväll både torsdag och fredag denna vecka. Hur ser det ut för er och vilken dag föredrar ni? :)

**Comment by karlek** [comment]
Torsdag och fredag funkar för mig med, inga speciella preferenser men röstar torsdag 👌

**Comment by mewmew** [comment]
Hej boyooos. Var sjukt kul att ses igår! Känner såhär dagen efter att halsen behöver lite vila, förmodligen eftersom vi inte körde jogï hemma hos er. Tänkte därför höra, vad tror ni om bastu nästa vecka på tors? (Eller annan dag om det fungerar bättre). Jag bokar prel tors den 15e, så kan vi basta och fixa middag tillsammans då.

**Comment by karlek** [comment]
Funkar för mig :camel:

**Comment by godbit** [comment]
Kan inte torsdag nästa vecka :disappointed: 

Kan dock onsdagen eller fredagen (bortsett från att vi måste ha en paladins stream på standby då :wink:)

**Comment by karlek** [comment]
Kan flytta min thing jag har på onsdag till torsdag så, kan vi köra onsdag nästa vecka!

**Comment by mewmew** [comment]
Fint, då kör vi på ons istället! Bastun är bokad :)

![2018-11-06-151058_696x493_scrot](https://user-images.githubusercontent.com/1414531/48069638-38fa9f80-e1d6-11e8-8299-6cf4361162a5.png)

**Comment by karlek** [comment]
Robin kunde inte fredag

**Edit:** då Robin är i Danmark ^^
